id                                           =>
series_id – Foreign key to the series table.=>
season_id – Foreign key to the seasons table.=>
episode_number=>
title=>
release_date=>
duration=>
plot_summary=>
poster_url=>
trailer_url=>
views_count=>
imdb_rating=>
license_start_date=>
license_end_date=>
available_resolutions=>
available_in_regions=>
created_at=>
updated_at=>