id                           =>
series_id=>
season_number=>
release_date=>
total_episodes=>
plot_summary=>
poster_url=>
trailer_url=>
views_count=>
license_start_date=>
license_end_date=>
available_resolutions=>
available_in_regions=>
created_at=>
updated_at=>
